# Generated by Django 3.0.6 on 2020-05-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_expiracao',
            field=models.DateTimeField(),
        ),
    ]
