# Generated by Django 3.0.6 on 2020-05-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200528_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_expiracao',
            field=models.DateField(),
        ),
    ]
